# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n\rRawTradeEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x07secType\x18\x02 \x01(\x0e\x32\x08.SecType\x12\x1b\n\x0elastTradePrice\x18\x03 \x01(\x02H\x00\x88\x01\x01\x12\x34\n\x0btradingTime\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x34\n\x0btradingDate\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02\x88\x01\x01\x42\x11\n\x0f_lastTradePriceB\x0e\n\x0c_tradingTimeB\x0e\n\x0c_tradingDate\"\xcc\x01\n\nTradeEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08\x65xchange\x18\x03 \x01(\t\x12\x19\n\x07sectype\x18\x04 \x01(\x0e\x32\x08.SecType\x12\x16\n\x0elasttradeprice\x18\x05 \x01(\x02\x12.\n\nlastUpdate\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tlastTrade\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x17\n\x07SecType\x12\x05\n\x01I\x10\x00\x12\x05\n\x01\x45\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SECTYPE._serialized_start=503
  _SECTYPE._serialized_end=526
  _RAWTRADEEVENT._serialized_start=52
  _RAWTRADEEVENT._serialized_end=294
  _TRADEEVENT._serialized_start=297
  _TRADEEVENT._serialized_end=501
# @@protoc_insertion_point(module_scope)
